version: '3.8'

services:
  flask-app:
    image: ${FLASK_APP_IMAGE}
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    container_name: flask-app
    networks:
      - my-custom-network
    volumes:
      - flask-data:/app/data
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  nginx:
    image: ${NGINX_IMAGE}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      flask-app:
        condition: service_healthy
    networks:
      - my-custom-network
    volumes:
      - ./nginx/html:/usr/share/nginx/html   # Mount the custom HTML
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
    ports:
      - "80:80"
    command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"

    restart: "on-failure"

networks:
  my-custom-network:
    driver: bridge

volumes:
  flask-data:
  nginx-data:
